# Generated by Django 4.1.7 on 2023-02-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friend_friend_alter_friend_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='from_user',
            new_name='from_profile',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='to_user',
            new_name='to_profile',
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('from_profile', 'to_profile')},
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, through='friends.FriendRequest', to='friends.profile'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Accepted'), ('d', 'Declined')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='message',
        ),
    ]
