# Generated by Django 4.1.7 on 2023-02-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_rename_from_user_friendrequest_from_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Accepted')], default='p', max_length=1),
        ),
    ]
