# Generated by Django 4.1.7 on 2023-03-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0008_alter_profile_bio_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
