# Generated by Django 4.1.7 on 2023-02-22 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_taskinstance_time_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_to_repeat',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
