# Generated by Django 4.1.7 on 2023-02-23 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskcategory_options_alter_task_time_to_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_to_repeat',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
