# Generated by Django 4.1.7 on 2023-02-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_time_to_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='task_photos'),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending Approval'), ('ACTIVE', 'Active')], default='ACTIVE', max_length=9),
        ),
    ]
