# Generated by Django 4.1.7 on 2023-02-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskinstance_photo_alter_taskinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
