# Generated by Django 4.1.7 on 2023-02-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_alter_profile_image'),
        ('tasks', '0008_remove_taskinstance_user_taskinstance_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='friends.profile'),
        ),
    ]
