# Generated by Django 4.1.7 on 2023-03-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_taskinstance_user_taskinstance_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='origin_message',
            field=models.CharField(default='This task is available', max_length=50),
        ),
    ]
