# Generated by Django 4.1.7 on 2023-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_taskinstance_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
