# Generated by Django 4.1.7 on 2023-03-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_origin_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='origin_message',
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='origin_message',
            field=models.CharField(default='This task is available', max_length=50),
        ),
    ]
