# Generated by Django 4.1.7 on 2023-02-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_alter_profile_image'),
        ('tasks', '0010_taskinstance_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinstance',
            name='reported',
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='reports', to='friends.profile'),
        ),
    ]
