# Generated by Django 4.1.7 on 2023-02-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_taskinstance_reported_taskinstance_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
