# Generated by Django 4.1.7 on 2023-03-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_task_origin_message_and_more'),
        ('tasks', '0012_taskinstance_location'),
    ]

    operations = [
    ]
