# Generated by Django 4.1.7 on 2023-03-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rarity',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Silver'), (3, 'Gold')], default=1),
        ),
    ]
