# Generated by Django 4.1.7 on 2023-03-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_task_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='ai_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
