# Generated by Django 4.1.7 on 2023-03-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_task_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bomb_time_limit',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_bomb',
            field=models.BooleanField(default=False),
        ),
    ]
