# Generated by Django 4.1.7 on 2023-03-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_task_bomb_time_limit_task_is_bomb'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='tagged_whom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
