# Generated by Django 4.1.7 on 2023-03-16 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0017_taskinstance_ai_tag"),
        ("tasks", "0019_alter_taskinstance_status"),
    ]

    operations = []
