# Generated by Django 4.1.7 on 2023-03-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_merge_20230316_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='can_user_self_assign',
            field=models.BooleanField(default=True),
        ),
    ]
