# Generated by Django 4.1.7 on 2023-02-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_alter_friendrequest_status'),
        ('leagues', '0002_league_description_league_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='leagues', to='friends.profile'),
        ),
    ]
