# Generated by Django 4.1.7 on 2023-03-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='notification_read',
        ),
    ]
