# Generated by Django 4.1.7 on 2023-03-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notifications_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
