name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to production
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@on.chrlie.net:22/sustainability'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  worker:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
       
      - name: Deploy to production
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@on.chrlie.net:22/worker'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
